### ISSUE TITLE
windows能用不

### ISSUE THREAD

**Issue by qianlihu8906** [NingShenTian/SerialHelper#1]
windows能用不？串口号是自动枚举么？还更新不

**Comment by NingShenTian** [comment]
能，你改改打开串口的地方。



发自我的小米手机
在 qianlihu <notifications@github.com>，2017年2月3日 下午4:12写道：

windows能用不？串口号是自动枚举么？还更新不

**Comment by NingShenTian** [comment]
需要改串口，Linux的前面加了/dev。Windows不需要。



发自我的小米手机
在 qianlihu <notifications@github.com>，2017年2月7日 上午9:17写道：

Closed #1<https://github.com/NingShenTian/SerialHelper/issues/1>.

**Comment by NingShenTian** [comment]
已经修改了，试试吧。主要修改了mainwindow.cpp，增加了一个宏，判断了一下当前系统。
